#!/usr/bin/env python3
"""
Environment Setup Script for Training Monkey Flask App
This script helps you set up the necessary environment variables for local development.
"""

import os
import secrets
from pathlib import Path

def create_env_file():
    """Create a .env file with default values for local development"""
    
    env_file = Path('.env')
    
    if env_file.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/n): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return
    
    # Generate a secure secret key
    secret_key = secrets.token_hex(32)
    
    env_content = f"""# Training Monkey Flask App - Environment Variables
# Generated by setup_environment.py

# =============================================================================
# FLASK CONFIGURATION
# =============================================================================
SECRET_KEY={secret_key}
FLASK_ENV=development
FLASK_DEBUG=True

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
# For local development (SQLite)
DB_PATH=../training_data.db

# For production (PostgreSQL) - uncomment and set if using cloud database
# DATABASE_URL=postgresql://username:password@host:port/database

# =============================================================================
# STRAVA API CONFIGURATION
# =============================================================================
# Get these from https://www.strava.com/settings/api
# STRAVA_CLIENT_ID=your-strava-client-id
# STRAVA_CLIENT_SECRET=your-strava-client-secret

# =============================================================================
# GOOGLE CLOUD CONFIGURATION (for production)
# =============================================================================
# Only needed if using Google Cloud services
# GOOGLE_CLOUD_PROJECT=your-google-cloud-project-id

# =============================================================================
# ANTHROPIC AI CONFIGURATION (for LLM recommendations)
# =============================================================================
# Get this from https://console.anthropic.com/
# ANTHROPIC_API_KEY=your-anthropic-api-key

# =============================================================================
# DEPLOYMENT CONFIGURATION
# =============================================================================
# Port for the Flask app (default: 8080 for production, 5000 for development)
PORT=5000
"""
    
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print("✅ .env file created successfully!")
    print(f"📁 Location: {env_file.absolute()}")
    print()
    print("🔧 Next steps:")
    print("1. Edit the .env file to add your API keys")
    print("2. Run: python start_dev_server.ps1")
    print()

def check_requirements():
    """Check if required packages are installed"""
    print("🔍 Checking required packages...")
    
    required_packages = [
        'flask',
        'flask-login',
        'requests',
        'anthropic',
        'google-cloud-secret-manager'
    ]
    
    missing_packages = []
    
    for package in required_packages:
        try:
            __import__(package.replace('-', '_'))
            print(f"✅ {package}")
        except ImportError:
            print(f"❌ {package} - MISSING")
            missing_packages.append(package)
    
    if missing_packages:
        print()
        print("⚠️  Missing packages detected!")
        print("Install them with:")
        print(f"pip install {' '.join(missing_packages)}")
        print()
        print("Or install all requirements:")
        print("pip install -r strava_requirements.txt")
    else:
        print()
        print("✅ All required packages are installed!")

def main():
    print("🚀 Training Monkey - Environment Setup")
    print("=" * 50)
    print()
    
    # Check requirements
    check_requirements()
    print()
    
    # Create .env file
    print("📝 Setting up environment variables...")
    create_env_file()
    
    print("🎉 Setup complete!")
    print()
    print("📚 For more information, see:")
    print("- docs/LOCAL_DEVELOPMENT_SETUP.md")
    print("- docs/QUICK_REFERENCE.md")

if __name__ == '__main__':
    main()


