#!/usr/bin/env python3
"""
Setup script for local database connection to Google Cloud PostgreSQL
This script helps configure your local development environment to connect to the cloud database.
"""

import os
import sys
from pathlib import Path

def create_local_env_file():
    """Create a .env file for local development with database connection"""
    
    # Get the project root directory
    project_root = Path(__file__).parent.parent
    app_dir = project_root / "app"
    env_file = app_dir / ".env"
    
    print("🔧 Setting up local database connection to Google Cloud PostgreSQL...")
    print(f"📁 Project root: {project_root}")
    print(f"📁 App directory: {app_dir}")
    print(f"📁 Environment file: {env_file}")
    print()
    
    # Check if .env already exists
    if env_file.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("❌ Setup cancelled.")
            return False
    
    # Get database connection details
    print("📋 Please provide your Google Cloud PostgreSQL connection details:")
    print()
    
    # Use the known connection details from the deployment script
    default_host = "10.109.208.9"
    default_port = "5432"
    default_database = "train-d"
    default_username = "appuser"
    
    print(f"Default values from deployment script:")
    print(f"  Host: {default_host}")
    print(f"  Port: {default_port}")
    print(f"  Database: {default_database}")
    print(f"  Username: {default_username}")
    print()
    
    use_defaults = input("Use these default values? (Y/n): ").strip().lower()
    
    if use_defaults in ['', 'y', 'yes']:
        host = default_host
        port = default_port
        database = default_database
        username = default_username
        password = input("Enter database password: ").strip()
    else:
        host = input("Database host: ").strip() or default_host
        port = input("Database port: ").strip() or default_port
        database = input("Database name: ").strip() or default_database
        username = input("Database username: ").strip() or default_username
        password = input("Database password: ").strip()
    
    # Get other configuration
    print()
    print("📋 Other configuration:")
    strava_client_id = input("Strava Client ID (optional): ").strip()
    strava_client_secret = input("Strava Client Secret (optional): ").strip()
    anthropic_api_key = input("Anthropic API Key (optional): ").strip()
    
    # Generate a secret key
    import secrets
    secret_key = secrets.token_urlsafe(32)
    
    # Create the .env file content
    env_content = f"""# Training Monkey Flask App - Local Development Environment
# Generated by setup_local_database_connection.py

# =============================================================================
# FLASK CONFIGURATION
# =============================================================================
SECRET_KEY={secret_key}
FLASK_ENV=development
FLASK_DEBUG=True
PORT=5000

# =============================================================================
# DATABASE CONFIGURATION - Google Cloud PostgreSQL
# =============================================================================
DATABASE_URL=postgresql://{username}:{password}@{host}:{port}/{database}

# =============================================================================
# GOOGLE CLOUD CONFIGURATION
# =============================================================================
GOOGLE_CLOUD_PROJECT=dev-ruler-460822-e8

# =============================================================================
# STRAVA API CONFIGURATION
# =============================================================================
"""
    
    if strava_client_id:
        env_content += f"STRAVA_CLIENT_ID={strava_client_id}\n"
    else:
        env_content += "# STRAVA_CLIENT_ID=your-strava-client-id\n"
    
    if strava_client_secret:
        env_content += f"STRAVA_CLIENT_SECRET={strava_client_secret}\n"
    else:
        env_content += "# STRAVA_CLIENT_SECRET=your-strava-client-secret\n"
    
    env_content += """
# =============================================================================
# ANTHROPIC AI CONFIGURATION (Optional)
# =============================================================================
"""
    
    if anthropic_api_key:
        env_content += f"ANTHROPIC_API_KEY={anthropic_api_key}\n"
    else:
        env_content += "# ANTHROPIC_API_KEY=your-anthropic-api-key\n"
    
    # Write the .env file
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        
        print()
        print("✅ .env file created successfully!")
        print(f"📁 Location: {env_file}")
        print()
        print("🔧 Next steps:")
        print("1. Install dependencies: pip install -r strava_requirements.txt")
        print("2. Test database connection: python test_database_connection.py")
        print("3. Start development server: python start_dev_server.ps1")
        print()
        
        return True
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False

def test_database_connection():
    """Test the database connection"""
    print("🔍 Testing database connection...")
    
    try:
        # Add the app directory to the Python path
        app_dir = Path(__file__).parent.parent / "app"
        sys.path.insert(0, str(app_dir))
        
        # Import and test the database connection
        from db_utils import get_db_connection
        
        with get_db_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute("SELECT version();")
                version = cursor.fetchone()
                print(f"✅ Database connection successful!")
                print(f"📊 PostgreSQL version: {version[0]}")
                
                # Test a simple query
                cursor.execute("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public';")
                table_count = cursor.fetchone()
                print(f"📋 Tables in database: {table_count[0]}")
                
                return True
                
    except Exception as e:
        print(f"❌ Database connection failed: {e}")
        print()
        print("🔧 Troubleshooting:")
        print("1. Check that your .env file has the correct DATABASE_URL")
        print("2. Verify your Google Cloud SQL instance is running")
        print("3. Ensure your IP is whitelisted in Cloud SQL")
        print("4. Check that the database credentials are correct")
        return False

def main():
    """Main setup function"""
    print("🚀 Training Monkey - Local Database Connection Setup")
    print("=" * 60)
    print()
    
    # Create .env file
    if not create_local_env_file():
        return
    
    # Test connection
    print()
    test_connection = input("Test database connection now? (Y/n): ").strip().lower()
    if test_connection in ['', 'y', 'yes']:
        test_database_connection()

if __name__ == "__main__":
    main()
